# Generated by Django 3.0.2 on 2020-01-24 19:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200124_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_title', models.CharField(max_length=50, verbose_name='Суть вопроса')),
                ('q_content', models.CharField(max_length=200, verbose_name='Вопрос')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='final_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 25, 19, 10, 45, 489285, tzinfo=utc), verbose_name='Дата окончания'),
        ),
        migrations.RemoveField(
            model_name='question',
            name='person_choice',
        ),
        migrations.AddField(
            model_name='question',
            name='person_choice',
            field=models.ForeignKey(blank=True, help_text='Выберите участников голосования', null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Choice', verbose_name='Выберите участников'),
        ),
        migrations.AddField(
            model_name='choice',
            name='questions',
            field=models.ManyToManyField(help_text='Укажите, в какие вопросы хотите добавить участника', through='polls.Question', to='polls.Quest', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Quest'),
        ),
    ]
