# Generated by Django 3.0.2 on 2020-01-24 19:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200124_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='final_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 25, 19, 12, 8, 424497, tzinfo=utc), verbose_name='Дата окончания'),
        ),
    ]
