# Generated by Django 3.0.2 on 2020-01-25 10:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200124_2244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='questions',
        ),
        migrations.AddField(
            model_name='choice',
            name='questions',
            field=models.ForeignKey(blank=True, help_text='Укажите, в какой вопрос хотите добавить участника', null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='final_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 26, 10, 12, 30, 198887, tzinfo=utc), verbose_name='Дата окончания'),
        ),
    ]
