# Generated by Django 3.0.2 on 2020-01-26 17:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200126_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='final_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 27, 17, 25, 39, 441718, tzinfo=utc), verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 26, 17, 25, 39, 441718, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
