# Generated by Django 3.0.2 on 2020-01-26 18:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200126_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='final_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 27, 18, 19, 14, 827350, tzinfo=utc), verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 26, 18, 19, 14, 827350, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
