# Generated by Django 3.0.2 on 2020-01-26 19:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20200126_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='final_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 27, 19, 58, 10, 802102, tzinfo=utc), verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 26, 19, 58, 10, 802102, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
