# Generated by Django 3.0.2 on 2020-01-26 19:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20200126_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='final_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 27, 19, 59, 7, 32678, tzinfo=utc), verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 26, 19, 59, 7, 32678, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
