# Generated by Django 3.0.2 on 2020-01-27 11:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20200127_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='photo_person',
            field=models.ImageField(blank=True, upload_to='polls/person/photos/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='final_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 1, 28, 11, 30, 14, 89555, tzinfo=utc), verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 27, 11, 30, 14, 89555, tzinfo=utc), verbose_name='Дата публикации'),
        ),
    ]
