# Generated by Django 3.0.2 on 2020-02-03 16:51

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20200127_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='age',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='photo_person',
            field=models.ImageField(blank=True, null=True, upload_to='polls/person/photos/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='final_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 4, 16, 51, 44, 140114, tzinfo=utc), verbose_name='Дата окончания'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации'),
        ),
    ]
