# Generated by Django 3.0.2 on 2020-02-03 16:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20200203_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='age',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='question',
            name='final_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 4, 16, 54, 52, 206316, tzinfo=utc), verbose_name='Дата окончания'),
        ),
    ]
