# Generated by Django 3.0.2 on 2020-02-03 17:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20200203_1958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='age',
        ),
        migrations.AlterField(
            model_name='question',
            name='final_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 4, 17, 0, 40, 366083, tzinfo=utc), verbose_name='Дата окончания'),
        ),
    ]
