# Generated by Django 3.0.2 on 2020-02-03 17:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20200203_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='age',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='question',
            name='final_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 2, 4, 17, 2, 43, 360498, tzinfo=utc), verbose_name='Дата окончания'),
        ),
    ]
